### PR TITLE
reduce memory size of image using '(unsigned-byte 8) array instead of

### PR DESCRIPTION
**Pull request by mgi**
generic integer array.

### CODE REVIEW

**Comment by mgi** [comment]
This was lightly tested (decode/encode) on some relatively big images (> 12 Mpix) that used to kill sbcl.

**Comment by xach** [comment]
Is there a performance impact?

**Comment by mgi** [comment]
Zach Beane <notifications@github.com> writes:

> Is there a performance impact?

Hum. I've overlooked this but yes there is one :-/
Here is the (time) for decode and then encode of a 12Mpix file before my
patch:

Evaluation took:
  3.626 seconds of real time
  3.620000 seconds of total run time (3.410000 user, 0.210000 system)
  [ Run times consist of 0.490 seconds GC time, and 3.130 seconds non-GC time. ]
  99.83% CPU
  12,057,404,560 processor cycles
  416,105,648 bytes consed
  
Evaluation took:
  2.252 seconds of real time
  2.250000 seconds of total run time (2.220000 user, 0.030000 system)
  [ Run times consist of 0.140 seconds GC time, and 2.110 seconds non-GC time. ]
  99.91% CPU
  7,487,123,600 processor cycles
  77,354,336 bytes consed

and after:

Evaluation took:
  5.087 seconds of real time
  5.080000 seconds of total run time (5.060000 user, 0.020000 system)
  99.86% CPU
  16,913,627,620 processor cycles
  52,749,104 bytes consed
  
Evaluation took:
  4.163 seconds of real time
  4.160000 seconds of total run time (4.130000 user, 0.030000 system)
  [ Run times consist of 0.010 seconds GC time, and 4.150 seconds non-GC time. ]
  99.93% CPU
  13,845,934,190 processor cycles
  77,354,288 bytes consed

But to be able, to load such an image into sbcl, I had to increase the
dynamic-space-size to 1000 MB as the resulting array is about 400 MB in
size (before my patch).
-- 
Manuel Giraud

**Comment by varjagg** [comment]
Interesting. I do remember going with simple vectors precisely for the distinct performance advantage over the adjustable/fillable arrays. 

Wonder if it's possible to improve on both fronts here with declaring them as simple arrays with the element type specifier.

**Comment by varjagg** [comment]
OK, I found this: https://github.com/froggey/cl-jpeg/commit/b29a0bbe92157e4806ebc4eb62b301c75e65430e

Manuel, would you try a similar simple-array type declaration in your patch and see how that goes?

**Comment by mgi** [comment]
I tried this and declaring all those buffers as (simple-array uint8 *),
the decode/encode time is reduced a bit (but not as fast as it was):

Evaluation took:
  4.263 seconds of real time
  4.270000 seconds of total run time (4.230000 user, 0.040000 system)
  [ Run times consist of 0.010 seconds GC time, and 4.260 seconds non-GC time. ]
  100.16% CPU
  14,173,459,520 processor cycles
  52,772,704 bytes consed
  
Evaluation took:
  3.686 seconds of real time
  3.690000 seconds of total run time (3.670000 user, 0.020000 system)
  [ Run times consist of 0.010 seconds GC time, and 3.680 seconds non-GC time. ]
  100.11% CPU
  12,259,058,580 processor cycles
  77,354,736 bytes consed

It might be something that is not fully optimized in sbcl. The patch you
have linked is simpler than mine: maybe this one should be pulled
instead, no?
-- 
Manuel Giraud

**Comment by varjagg** [comment]
OK, have a look at this:

http://paste.lisp.org/display/155594#1

I ran it on CCL. Original paste is where we have 2x performance advantage of svref over aref. It seems to get even once we declare the type of the value in handle-aref as simple-array (see the annotation). 

I can get back to the issue later tomorrow, but if you can you run this quickly in your Lisp implementation and see if that holds that would be great.

**Comment by mgi** [comment]
Yes, svref is very fast on SBCL. First version of your code:

CL-USER> (test-svref)
Evaluation took:
  0.903 seconds of real time
  0.900000 seconds of total run time (0.900000 user, 0.000000 system)
  99.67% CPU
  3,001,885,660 processor cycles
  0 bytes consed

CL-USER> (test-aref)
Evaluation took:
  8.0000 seconds of real time
  7.990000 seconds of total run time (7.990000 user, 0.000000 system)
  99.88% CPU
  26,601,516,220 processor cycles
  0 bytes consed

Second version:

CL-USER> (test-svref)
Evaluation took:
  0.903 seconds of real time
  0.890000 seconds of total run time (0.890000 user, 0.000000 system)
  98.56% CPU
  3,002,036,410 processor cycles
  0 bytes consed

CL-USER> (test-aref)
Evaluation took:
  1.203 seconds of real time
  1.210000 seconds of total run time (1.210000 user, 0.000000 system)
  100.58% CPU
  4,001,066,030 processor cycles
  0 bytes consed

I was starting to dive into SBCL's deftransform (and such), but I think
I'll drown quickly.
-- 
Manuel Giraud

**Comment by varjagg** [comment]
OK, I merged Manuel's changes with changing the type from (simple-array 'uint8 *) to ..uint8 (*)), and it did cut on consing while incurring no performance penalty of note.

https://github.com/varjagg/cl-jpeg

Miguel if you can pull out of my fork and confirm it worked, I'll make another pull request to sharplispers.

**Comment by mgi** [comment]
Oups, forgot to get back to you about this. So your version is fine, but now on sbcl it's the (safety 1) that cause a great performance drop. Same test same image as before on this thread.

With (safety 0):
Evaluation took:
  4.264 seconds of real time
  4.260000 seconds of total run time (4.220000 user, 0.040000 system)
  99.91% CPU
  14,176,190,410 processor cycles
  52,772,704 bytes consed
  
Evaluation took:
  3.691 seconds of real time
  3.700000 seconds of total run time (3.680000 user, 0.020000 system)
  [ Run times consist of 0.040 seconds GC time, and 3.660 seconds non-GC time. ]
  100.24% CPU
  12,274,182,440 processor cycles
  77,354,192 bytes consed

With (safety 1):
Evaluation took:
  6.892 seconds of real time
  6.810000 seconds of total run time (6.740000 user, 0.070000 system)
  [ Run times consist of 0.010 seconds GC time, and 6.800 seconds non-GC time. ]
  98.81% CPU
  22,918,538,620 processor cycles
  52,805,104 bytes consed
  
Evaluation took:
  5.497 seconds of real time
  5.460000 seconds of total run time (5.310000 user, 0.150000 system)
  99.33% CPU
  18,279,301,480 processor cycles
  10,648,032 bytes consed

**Pull request merged**
